version: "3.8"
networks:
  cookie-monster:
    driver: bridge
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    networks:
      - cookie-monster
    # environment:
    #   - POSTGRES_HOST=192.168.1.7
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=gjmptwad



  frontend:
    build: ./frontend
    container_name: frontend_react
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    networks:
      - cookie-monster   # Set the environment variable to use port 3001

    stdin_open: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      - cookie-monster

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - cookie-monster

