version: "3.8"
networks:
  cookie-monster:
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    networks:
      - cookie-monster
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - NODE_PORT=3000
     - ELASTIC_URL=http://elasticsearch:9200
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    # environment:
    #   - POSTGRES_HOST=192.168.1.7
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=gjmptwad



  frontend:
    build: ./frontend
    container_name: frontend_react
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    networks:
      - cookie-monster   # Set the environment variable to use port 3001

    stdin_open: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    logging:
      driver: none
    ports:
      - '9200:9200'
    networks:
      - cookie-monster

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - cookie-monster

